project:
  type: book

book:
  title: "Curso: Geoanálisis"
  subtitle: "Diplomado en Ciencia de Datos para Políticas Públicas 2023"
  # affiliation-title: "Universidad Adolfo Ibáñez - Chile"
  author: "Denis Berroeta González (denis.berroeta@uai.cl)"
  date: "2023-10-17"
  language: "es"
  # number-sections: 3
  page-footer: 
    left: "Copyright 2023, Denis Berroeta" 
  chapters:
    - index.qmd
    - intro_estad_esp.qmd
    - datos_espaciales.qmd
    - datos_vectoriales.qmd
    - raster.qmd
    - inferencia.qmd
    - autocorrelacion.qmd
    # - regresion_espacial.qmd
    - part: "Tareas"
      chapters:
        - tarea_1.qmd
        - tarea_2.qmd
    - part: "Anexos"
      chapters:
        - espacial_r.qmd
        - luces_nocturnas.qmd
        - john_snow.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    css: styles/style.css
    fig-align: "center"
    fig-cap-location: "margin"
    tab-cap-location: "left"
    mailto: "denis.berroeta@uai.cl"
  
execute:
  warning: false
  
editor: source
always_allow_html: true



