project:
  type: book

book:
  title: "Curso: Geoanálisis"
  subtitle: "Diplomado en Ciencia de Datos para Políticas Públicas 2024"
  # affiliation-title: "Universidad Adolfo Ibáñez - Chile"
  author: "Denis Berroeta González (denis.berroeta@uai.cl)"
  date: "2024-10-05"
  language: "es"
  # number-sections: 3
  page-footer: 
    left: "Copyright 2024, Denis Berroeta" 
  chapters:
    - index.qmd
    - intro_estad_esp.qmd
    - datos_espaciales.qmd
    - datos_vectoriales.qmd
    #- raster.qmd
    #- inferencia.qmd
    #- autocorrelacion.qmd
    #- regresion_espacial.qmd
    #- part: "Tareas"
    # chapters:
    #   - tarea_1.qmd
    #   - tarea_2.qmd
    - part: "Anexos"
      chapters:
        - r_project.qmd
        # - espacial_r.qmd
          #   - luces_nocturnas.qmd
          #- john_snow.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    css: styles/style.css
    fig-align: "center"
    fig-cap-location: "margin"
    tab-cap-location: "left"
    mailto: "denis.berroeta@uai.cl"
    code-block-bg: true
    code-block-border-left: "#31BAE9"
  
execute:
  warning: false
  
editor: source
always_allow_html: true



